name: Create Release and Build Binaries

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.1'

      - name: Build binaries
        run: |
          for GOOS in linux darwin windows; do
            for GOARCH in amd64 arm64; do
              export GOOS=$GOOS
              export GOARCH=$GOARCH
              go build -o ./bin/todo-cli-$GOOS-$GOARCH main.go
            done
          done

      - name: Upload Release Binaries
        uses: softprops/action-gh-release@v1
        with:
          files: ./bin/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}