name: Build Binaries

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64]
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.1'
      - name: Install build essentials
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Build binaries
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: 1
        run: |
          go build -o ./bin/todo-cli-${{ matrix.goos }}-${{ matrix.goarch }} main.go

      - name: Verify build output
        run: test -f ./bin/todo-cli-${{ matrix.goos }}-${{ matrix.goarch }}

      - name: Upload Release Binaries
        uses: softprops/action-gh-release@v1
        with:
          files: bin/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Notify about the release
        run: echo "Binaries have been uploaded to the release!"